Data Cleaning and Processing

This dataset was obtained from Kaggle, capturing daily lifestyle behaviors of individuals and shwos their carbon footprint. This dataset contains modes of transportation, energy usage, food diet, screentime, waste generated, and eco-friendly action counts, all contibuting to their carbon footprint and following classification (Low, Medium, or High) impact level.

The objective of this notebook is to evaluate the data quality by looking for missing, N/A, outliers, and summary statistics before moving onto the exploratory data portion of the project.

In [3]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/personal_carbon_footprint_behavior.csv')

The first step is to load the Kaggle dataset into a Pandas Dataframe to inspect.

In [4]:
df.shape

(1400, 12)

In [4]:
df.head()

,user_id,day_type,transport_mode,distance_km,electricity_kwh,renewable_usage_pct,food_type,screen_time_hours,waste_generated_kg,eco_actions,carbon_footprint_kg,carbon_impact_level
0,1,Weekend,EV,1.55,6.12,0,Non-Veg,2.4,0.70,1,11.03,High
1,1,Weekend,Walk,10.04,4.50,0,Mixed,4.1,0.54,1,7.44,Medium
2,1,Weekday,Walk,15.27,2.81,0,Mixed,4.0,0.51,1,6.01,Medium
3,1,Weekend,Walk,0.50,10.16,0,Mixed,6.3,0.73,0,12.70,High
4,1,Weekend,Walk,3.60,5.02,50,Mixed,5.1,0.64,0,6.33,Medium

Based on this quick look, there appear to be no missing values that would negatively impact and skew results drawn later on.

In [9]:
df.isna().sum()

user_id                0
day_type               0
transport_mode         0
distance_km            0
electricity_kwh        0
renewable_usage_pct    0
food_type              0
screen_time_hours      0
waste_generated_kg     0
eco_actions            0
carbon_footprint_kg    0
carbon_impact_level    0
dtype: int64

Again, we see no missing values within any of the columns. Nothing is necessary to change here.

In [10]:
df.describe()

,user_id,distance_km,electricity_kwh,renewable_usage_pct,screen_time_hours,waste_generated_kg,eco_actions,carbon_footprint_kg
count,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000
mean,100.500000,9.106071,5.951443,31.589286,5.521786,0.703200,1.144286,7.980236
std,57.754936,4.734692,1.993266,30.598496,2.018918,0.236415,1.019066,2.657858
min,1.000000,0.500000,2.000000,0.000000,2.000000,0.100000,0.000000,1.790000
25%,50.750000,5.662500,4.530000,0.000000,3.800000,0.550000,0.000000,6.080000
50%,100.500000,9.180000,5.925000,25.000000,5.550000,0.705000,1.000000,7.835000
75%,150.250000,12.510000,7.290000,50.000000,7.300000,0.860000,2.000000,9.830000
max,200.000000,22.670000,12.270000,100.000000,9.000000,1.510000,5.000000,16.020000

The summary statistics above allow us to view possible discrepancies within the data. Min an max values look reasonable within their features. Similarly, the ranges and distributions follow this trend. No crazy values here.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              1400 non-null   int64
 1   day_type             1400 non-null   object
 2   transport_mode       1400 non-null   object
 3   distance_km          1400 non-null   float64
 4   electricity_kwh      1400 non-null   float64
 5   renewable_usage_pct  1400 non-null   int64
 6   food_type            1400 non-null   object
 7   screen_time_hours    1400 non-null   float64
 8   waste_generated_kg   1400 non-null   float64
 9   eco_actions          1400 non-null   int64
 10  carbon_footprint_kg  1400 non-null   float64
 11  carbon_impact_level  1400 non-null   object
dtypes: float64(5), int64(3), object(4)
memory usage: 131.4+ KB

Here, the data presents its data type, following the standard type as expected. No conversions are required here.

In [6]:
df.duplicated().sum()

np.int64(0)

Cleaning Summary

None of the values within this dataset were removed as there were no out of place variables, null values, or outliers. No duplicates were observed, and data within the dataset follows reasonable value ranges. This data required no interference and is ready to be transfered to the next phase: exploratory data analysis. This thorough quality assessment confirmed that minimal preprocessing was required.